# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/gen_pic.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import logging

import yaml
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QThread, pyqtSignal

from gen_success import Ui_GenSuccessDialog

with open('./config/log.yaml', 'r') as f:
    config = yaml.safe_load(f.read())
    logging.config.dictConfig(config)

logger = logging.getLogger("uigenword")


class Ui_Gen_Word(object):
    def setupUi(self, Gen_Word):
        Gen_Word.setObjectName("Gen_Word")
        Gen_Word.setWindowModality(QtCore.Qt.WindowModal)
        Gen_Word.resize(429, 105)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Gen_Word.setWindowIcon(icon)
        self.progressBar = QtWidgets.QProgressBar(Gen_Word)
        self.progressBar.setGeometry(QtCore.QRect(20, 20, 401, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.pushButton = QtWidgets.QPushButton(Gen_Word)
        self.pushButton.setGeometry(QtCore.QRect(160, 60, 81, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Gen_Word)
        QtCore.QMetaObject.connectSlotsByName(Gen_Word)

    def retranslateUi(self, Gen_Pic):
        _translate = QtCore.QCoreApplication.translate
        Gen_Pic.setWindowTitle(_translate("Gen_Pic", "生成Word"))
        self.pushButton.setText(_translate("Gen_Pic", "生成Word"))

    def setData(self, picture):
        self.picture = picture
        self.picture.reload_config()
        self.progressBar.setMinimum(0)
        self.progressBar.setMaximum(self.picture.get_num())
        self.pushButton.clicked.connect(self.btnFunc)

    def btnFunc(self):
        logger.debug("开始生成word")
        self.thread = GenWordThread(self.picture)
        self.thread._signal.connect(self.signal_accept)
        logger.debug("生成word工作线程开始")
        self.picture.reload_config()
        self.thread.start()
        logger.debug("设置按钮不可用")
        self.pushButton.setEnabled(False)

    def signal_accept(self, msg):
        if (self.progressBar.value() == self.picture.get_num()):
            self.progressBar.setValue(0)
        logger.debug("accect signal : %s", msg)
        value = self.progressBar.value() + int(msg)
        logger.debug("signal value: %s", value)
        self.progressBar.setValue(value)
        if self.progressBar.value() == self.picture.get_num():
            self.window = QtWidgets.QMainWindow()
            self.gsuccess = Ui_GenSuccessDialog()
            self.gsuccess.setupUi(self.window)
            self.window.show()
            self.pushButton.setEnabled(True)
            _translate = QtCore.QCoreApplication.translate
            self.pushButton.setText(_translate("Gen_Word", "重新生成"))


class GenWordThread(QThread):
    _signal = pyqtSignal(int)

    def __init__(self, pic):
        super(GenWordThread, self).__init__()
        self.pic = pic

    def __del__(self):
        self.wait()

    def run(self):
        for name in self.pic.get_product_name():
            logger.debug("%s start gen word", name)
            self.pic.gen_word(name)
            logger.debug("%s gen word ok", name)
            self._signal.emit(1)


