version: 1
formatters:
  brief:
    format: "%(asctime)s - %(message)s"
  simple:
    format: "%(asctime)s - %(name)s - %(threadName)s - %(levelname)s - %(message)s"
handlers:
  console:
    class : logging.StreamHandler
    formatter: simple
    level: DEBUG
    stream: ext://sys.stdout
  file:
    class : logging.FileHandler
    formatter: simple
    level: DEBUG
    filename: debug.log
  totatingFile:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: error.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
loggers:
  picture:
    level: DEBUG
    handlers: [file, totatingFile]
  app:
    level: DEBUG
    handlers: [file, totatingFile]
  test:
    level: DEBUG
    handlers: [file, totatingFile]
  uigenpic:
    level: DEBUG
    handlers: [file, totatingFile]
  uigenword:
    level: DEBUG
    handlers: [file, totatingFile]
  uigendata:
    level: DEBUG
    handlers: [file, totatingFile]

root:
  level: DEBUG
  handlers: [console]